### ISSUE TITLE
Make Page Responsive

### ISSUE THREAD

**Issue by siladgey** [szpatrichard/disney-character-quiz#1]
**Description:**

The current design does not appear to be fully responsive on various screen sizes. This can lead to elements overlapping, being too large for smaller screens, or too small for larger screens. To enhance user experience across different devices, we need to update the CSS to ensure the layout adapts gracefully to different viewport sizes.

**Possible solution:**

- Consider implementing a mobile-first approach where styles are applied to smaller screens first and then progressively enhanced for larger screens.
- Use media queries to apply different styles depending on the viewport width.
- Replace fixed pixel widths with relative units.

**References:**

1. [Media Queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries)
2. [Flexible Layouts](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox)
3. [Responsive Design Basics:](https://developers.google.com/web/fundamentals/design-and-ux/responsive)

**Comment by Sky-De** [comment]
@szpatrichard assign this to me
